### ISSUE TITLE
Get next entry after using skip?

### ISSUE THREAD

**Issue by mario** [thrau/jarchivelib#39]
Hello,

so I'm trying to do seeking inside a .tar.gz and I've attempted to get offset of a certain file I  need, and I know its size.

                byte[] fileBytes = new byte[entrySize];
                stream2.read(fileBytes, entryOffset, entrySize);

However this doesn't seem to produce usable file at all.

Any ideas? Or maybe could I could "skip(entryOffset)" and then getCurrentEntry?

Thanks.

**Comment by mario** [comment]
I think what I actually need is ... can I get compressed size of a file from an archive when using stream?

**Comment by thrau** [comment]
Not using jarchivelib, this is certainly something for which you should the commons-compress API. How exactly the archive streams are structured is also dependent on the format. I'd suggest you have a look at the `ArchiveInputStream` implementations of commons-compress, such as [`TarArchiveInputStream`](https://github.com/apache/commons-compress/blob/trunk/src/main/java/org/apache/commons/compress/archivers/tar/TarArchiveInputStream.java)

**Comment by mario** [comment]
Ok, will take a look. What I'm trying to do is random access tgz so I can find & extract files faster, rather than going through everything. Will see what I can do.

**Comment by thrau** [comment]
Why don't you use the `ArchiveStream` and iterate over the entries? You can get their names without having to extract them and extract entries individually.
