### ISSUE TITLE
Need way to set LONGFILE_POSIX and BIGNUMBER_POSIX for TarArchiveOutputStream

### ISSUE THREAD

**Issue by pshapiro4claritas** [thrau/jarchivelib#41]
I'm trying to use the jarchivelib API to create a .tar.gz file and I need to set the LONGFILE_POSIX and BIGNUMBER_POSIX settings on the TarArchiveOutputStream. There may be a way to do this already using the API but I can't seem to figure it out. See http://commons.apache.org/proper/commons-compress/tar.html

The API looks great, it would be great if there were a way to use it with these settings.

Thanks!

**Comment by thrau** [comment]
Not using jarchivelib, which is really just convenience code. I would suggest to use commons-compress code directly for this..

**Comment by pshapiro4claritas** [comment]
Sure, I can do it by calling commons-compress directly. I was just thinking that if there was a way to get to the underlying `TarArchiveOutputStream` from the `ArchiveStream` then I could keep using the more convenient API.

**Comment by thrau** [comment]
The archive creation process using the `ArchiveOutputStream` is completely hidden behind the API, there is no way to access it. Also, the implementations are all package local, so you can't overwrite them (admittedly not the best design choice). I'm re-designing some of those mechanisms for a v2 to make it easier to handle specific archive entries, however this won't be public anytime soon. Sorry!

**Comment by pshapiro4claritas** [comment]
Thanks for the responses & I totally understand. It's your fault in the first place for making an API that streamlines commons-compress so well. :)

**Comment by mikeholler** [comment]
I would also really like to see this feature.
