### ISSUE TITLE
Add "NONE" compressor

### ISSUE THREAD

**Issue by scrobbleme** [thrau/jarchivelib#43]
It would be nice to have a compresser, which explicitly donates that there is explicitly no compression.

Main reason: it would be possible to always use the same method to create archivers using some dynamic mechanism.

**Comment by thrau** [comment]
i'm not quite sure i see the benefit. could you maybe illustrate the problem and the resulting solution with some code?

**Comment by scrobbleme** [comment]
The reason was to be able to always use the same method and no need from some if-statement, like this. this would also allow for better dynamic loading of the archiver.
```
Archiver archiver = ArchiverFactory.createArchiver(ArchiveFormat.TAR, CompressionType.GZIP);
Archiver archiver = ArchiverFactory.createArchiver(ArchiveFormat.ZIP, CompressionType.NONE);
```

But I have to admit, that I wasn't aware of the methot to get the archiver from the file extension, when submiting the issue. This at the end was enough for our problem.
