### ISSUE TITLE
Can not unzip soft link file correctly

### ISSUE THREAD

**Issue by baijian** [thrau/jarchivelib#44]
hi,when my xx.tar.gz file contains a soft link, after extract, the soft link turn a empty file.

**Comment by thrau** [comment]
yes this is on the feature list #40

**Comment by baijian** [comment]
what's the main difference between v2.x.x and v1.x.x?

**Comment by thrau** [comment]
i want to redesign the API completely in 2.0.0, but there's no clear concept yet. 1.0.0 should just be a major release of what is there now. if you find a solution for the symlink issue in the current codebase, i'll be happy to review it.
