### ISSUE TITLE
[discussion] Comparing against Apache Commons Compress

### ISSUE THREAD

**Issue by archenroot** [thrau/jarchivelib#59]
Could you briefly compare this library against Commons Compress framework (pros/cons) ? Maybe adding this into README.md file could be valuable.

**Comment by archenroot** [comment]
As per my understanding it could be seen as higher level API over commons compress by Apache, correct?

**Comment by thrau** [comment]
Yes.

> A simple archiving and compression library for Java that provides a thin and easy-to-use API layer on top of the powerful and feature-rich org.apache.commons.compress.

jarchivelib is just a utility that makes it easy to handle archives as java `File` objects. the commons compress api is highly flexible, but the default use case of extracting a local file to a directory requires quite a few lines of code and reading the docs. jarchivelib provides a simple idiomatic way of doing this.

**Comment by archenroot** [comment]
@thrau ok, thx for confirmation, I started using it anyway already as the core for my spring boot (data, rest, swagger) service with UI in Vaadin to manage our company data archiving process. I will be releasing it to the public on github as well.

**Comment by archenroot** [comment]
@thrau 

Hi buddy, 

so I started over and being implementing complete archiving solution, should be simple where I put your code into archive-core module and from now on I will be working on this module there. The microservice is running on SpringBoot, Spring Data JPA, Spring Data REST (for external calls) and provides built in GUI in Vaadin ( I have pro license, so there will be charts). The persistence will be in PostgreSQL builtin via Java wrapper, which is meant for rather unit tests, but i will use it as regulard embedded persistency wrapper for the service.
https://github.com/yandex-qatools/postgresql-embedded

Any hints for features to implement raise as issues in standard way.
https://github.com/archenroot/integration-commons_archive-service

I have done few initial commits, so there is still work to do, but I think next week will be finished the bare metal :-)
