### ISSUE TITLE
New releases on maven central?

### ISSUE THREAD

**Issue by Kindrat** [thrau/jarchivelib#65]
Are you going to deploy new releases to maven central? Any ETA or roadmap?

**Comment by thrau** [comment]
Thanks for reminding me. I'll release 0.8.0. in the next few days. Just need to find my credentials ...

**Comment by Kindrat** [comment]
I've copy-pasted sources to my project for now)

**Comment by valfirst** [comment]
For me the question is to keep or to drop this dependency.

**Comment by thrau** [comment]
i just haven't come round to set up the new keys for sonatype etc. i'll try and get it done by the end of today. sorry to keep you waiting.

**Comment by thrau** [comment]
released jarchivelib 0.8.0, should be in central in a couple of hours.
