### ISSUE TITLE
File permissions not saves

### ISSUE THREAD

**Issue by ghost** [thrau/jarchivelib#67]
I have tar.gz archive with file permissions. After extract it in folder in private android app directory i got incorrect permissions. 
But it works currectly with unix utilite `tar`

**Comment by thrau** [comment]
this was addressed a long time ago in #13 
could you describe your situation in more detail? i.e., what version of jarchivelib and android are you using? can you share a sample archive that you're having problems with?

**Comment by thrau** [comment]
@MisterGitHubber do you have any additional information on this? otherwise i will close the issue.
