### ISSUE TITLE
Upgrade to commons-compress 1.18

### ISSUE THREAD

**Issue by onilton** [thrau/jarchivelib#69]
The latest version commons-compress has new compression formats like Zstandard.

Are pull requests allowed to make jarchivelib work with 1.18 and the new formats?

Or is there some kind of timeline or milestones planned ahead for this?

**Comment by thrau** [comment]
somewhat relates to #22, and that jarchivelib still maintains compatibility with java 6 (new commons compress version require java 7). but i think it's really time to drop it. i always had in mind to release a major version before upgrading to java 7. so feel free to integrate the new formats and make pull requests. i might redirect them to a new branch or something.
