### ISSUE TITLE
[Question] Extract a .gz file

### ISSUE THREAD

**Issue by cldsnchz** [thrau/jarchivelib#78]
Is it possible to extract a .gz file (not .tar.gz)?

I get
`Unknown archive file extension .gz` 
when call
`Archiver logArchiver = ArchiverFactory.createArchiver(logFile);`

I tried several combinations but couldn't find a way to generate an Archiver that works for only .gz files.

**Comment by thrau** [comment]
Yes, it's possible to extract gzip compressed files. Unfortunately compressors aren't reconciled with the Archiver API nicely, but you can use the `Compressor` interface.

```java
Compressor compressor = CompressorFactory.createCompressor(logFile)
compressor.decompress(logFile, new File("path/to/target.txt"));
```

**Comment by cldsnchz** [comment]
Perfect, worked fine. 
Thanks!
